### ISSUE TITLE
3.3 bug

### ISSUE THREAD

**Issue by yuanshengaoshou114** [NotThorny/AttackModifier#11] opened 2022-12-16 21:05 UTC
Jar is https://github.com/YuukiPS/DockerGS
 Error Command at:
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot read field "skill" because "avatarToChange" is null

**Comment by NotThorny** [comment] 2022-12-17 04:25
Duplicate of #10 - when grasscutter officially updates to 3.3 then anything broken will be fixed. I unfortunately am not planning on updating for any specific non-official jar since it may conflict with official gc release, which is what this is made for.

**Closed as not planned by NotThorny** 2022-12-17 04:25 UTC
